# Generated by Django 5.1.2 on 2024-12-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipoluz', models.CharField(max_length=20)),
                ('tamano', models.CharField(max_length=20)),
                ('especie', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
            ],
        ),
    ]
